{% set name = "helics" %}
{% set version = "1.3.0" %}
{% set checksum = "d47759ac172d82c0eea75b34af8807e673ab5562a1cf3097cca6dc976a3c9c06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GMLC-TDC/HELICS-src/archive/v{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script_env:
      - CONDA_BLD_PATH

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.4.0
    - swig
    - ninja
    - boost-cpp
    - zeromq
    - python
  host:
    - python
    - boost-cpp
    - zeromq
  run:
    - python
    - boost-cpp
    - zeromq

test:
  imports:
    - helics

about:
  home: https://github.com/GMLC-TDC/HELICS-src
  license: BSD
  license_file: LICENSE
  license_family: BSD
  summary: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  description: 'Hierarchical Engine for Large-scale Infrastructure Co-Simulation (HELICS) framework'
  doc_url: http://gmlc-tdc.github.io/HELICS-src/index.html
  dev_url: https://github.com/GMLC-TDC/HELICS-src

extra:
  recipe-maintainers:
    - kdheepak
